import { RouterNode, NetworkLink } from '@/types/network';

export const INITIAL_NODES: RouterNode[] = [
  {
    id: 'C-A',
    label: 'Client A',
    name: 'Willow Cottage',
    role: 'client',
    x: 90,
    y: 190,
    status: 'online',
    ip: '192.168.1.101',
    description: 'Residential client sending interactive web & application requests.',
    queueLength: 0,
    maxQueue: 20,
    processedCount: 0,
    droppedCount: 0,
  },
  {
    id: 'C-B',
    label: 'Client B',
    name: 'Meadow Villa',
    role: 'client',
    x: 90,
    y: 450,
    status: 'online',
    ip: '192.168.1.102',
    description: 'Smart-home edge client streaming continuous telemetry packets.',
    queueLength: 0,
    maxQueue: 20,
    processedCount: 0,
    droppedCount: 0,
  },
  {
    id: 'R1',
    label: 'R1: West Gateway',
    name: 'West Gateway Intersection',
    role: 'router',
    x: 270,
    y: 280,
    status: 'online',
    ip: '10.0.1.1',
    description: 'Primary ingress router aggregating regional client traffic.',
    queueLength: 0,
    maxQueue: 35,
    processedCount: 0,
    droppedCount: 0,
  },
  {
    id: 'R2',
    label: 'R2: North Blvd',
    name: 'North Boulevard Roundabout',
    role: 'router',
    x: 470,
    y: 120,
    status: 'online',
    ip: '10.0.2.1',
    description: 'Scenic northern detour router with high bandwidth and low baseline traffic.',
    queueLength: 0,
    maxQueue: 30,
    processedCount: 0,
    droppedCount: 0,
  },
  {
    id: 'R3',
    label: 'R3: Central Crossway',
    name: 'Central Crossway Hub',
    role: 'router',
    x: 470,
    y: 300,
    status: 'online',
    ip: '10.0.3.1',
    description: 'High-speed central backbone crossway. Core transit node prone to congestion.',
    queueLength: 0,
    maxQueue: 40,
    processedCount: 0,
    droppedCount: 0,
  },
  {
    id: 'R4',
    label: 'R4: South Highway',
    name: 'South Highway Interchange',
    role: 'router',
    x: 470,
    y: 490,
    status: 'online',
    ip: '10.0.4.1',
    description: 'Southern arterial bypass connecting peripheral IoT traffic to core.',
    queueLength: 0,
    maxQueue: 30,
    processedCount: 0,
    droppedCount: 0,
  },
  {
    id: 'R5',
    label: 'R5: East Avenue',
    name: 'East Avenue Plaza',
    role: 'router',
    x: 680,
    y: 190,
    status: 'online',
    ip: '10.0.5.1',
    description: 'North-east egress router feeding directly into cloud server clusters.',
    queueLength: 0,
    maxQueue: 35,
    processedCount: 0,
    droppedCount: 0,
  },
  {
    id: 'R6',
    label: 'R6: Midtown Junction',
    name: 'Midtown Junction',
    role: 'router',
    x: 680,
    y: 430,
    status: 'online',
    ip: '10.0.6.1',
    description: 'South-east distribution router serving media streaming traffic.',
    queueLength: 0,
    maxQueue: 35,
    processedCount: 0,
    droppedCount: 0,
  },
  {
    id: 'R7',
    label: 'R7: Metro Exchange',
    name: 'Metro Exchange Tower',
    role: 'router',
    x: 870,
    y: 310,
    status: 'online',
    ip: '10.0.7.1',
    description: 'Ultra-fast core switching exchange bridging east hubs to data centers.',
    queueLength: 0,
    maxQueue: 50,
    processedCount: 0,
    droppedCount: 0,
  },
  {
    id: 'S-A',
    label: 'Server Alpha',
    name: 'Cloud Data Center',
    role: 'server',
    x: 1060,
    y: 190,
    status: 'online',
    ip: '172.16.100.1',
    description: 'Enterprise cloud computing and web services facility.',
    queueLength: 0,
    maxQueue: 100,
    processedCount: 0,
    droppedCount: 0,
  },
  {
    id: 'S-B',
    label: 'Server Beta',
    name: 'Streaming Vault',
    role: 'server',
    x: 1060,
    y: 450,
    status: 'online',
    ip: '172.16.200.2',
    description: 'High-capacity low-latency video streaming server.',
    queueLength: 0,
    maxQueue: 100,
    processedCount: 0,
    droppedCount: 0,
  },
];

export const INITIAL_LINKS: NetworkLink[] = [
  {
    id: 'C-A_R1',
    source: 'C-A',
    target: 'R1',
    bandwidthMbps: 100,
    baseLatencyMs: 4,
    currentLoad: 12,
    packetLossRate: 0.0,
    status: 'normal',
    name: 'Willow Access Road',
    vehiclesOnRoad: 0,
    failed: false,
  },
  {
    id: 'C-B_R1',
    source: 'C-B',
    target: 'R1',
    bandwidthMbps: 100,
    baseLatencyMs: 5,
    currentLoad: 15,
    packetLossRate: 0.0,
    status: 'normal',
    name: 'Meadow Lane',
    vehiclesOnRoad: 0,
    failed: false,
  },
  {
    id: 'C-B_R4',
    source: 'C-B',
    target: 'R4',
    bandwidthMbps: 80,
    baseLatencyMs: 8,
    currentLoad: 10,
    packetLossRate: 0.0,
    status: 'normal',
    name: 'South Valley Pass',
    vehiclesOnRoad: 0,
    failed: false,
  },
  {
    id: 'R1_R2',
    source: 'R1',
    target: 'R2',
    bandwidthMbps: 1000,
    baseLatencyMs: 12,
    currentLoad: 18,
    packetLossRate: 0.0,
    status: 'normal',
    name: 'North Arterialway',
    vehiclesOnRoad: 0,
    failed: false,
  },
  {
    id: 'R1_R3',
    source: 'R1',
    target: 'R3',
    bandwidthMbps: 2500,
    baseLatencyMs: 6,
    currentLoad: 28,
    packetLossRate: 0.0,
    status: 'normal',
    name: 'Grand Metro Highway',
    vehiclesOnRoad: 0,
    failed: false,
  },
  {
    id: 'R1_R4',
    source: 'R1',
    target: 'R4',
    bandwidthMbps: 1000,
    baseLatencyMs: 14,
    currentLoad: 15,
    packetLossRate: 0.0,
    status: 'normal',
    name: 'South Linkway',
    vehiclesOnRoad: 0,
    failed: false,
  },
  {
    id: 'R2_R5',
    source: 'R2',
    target: 'R5',
    bandwidthMbps: 1000,
    baseLatencyMs: 11,
    currentLoad: 16,
    packetLossRate: 0.0,
    status: 'normal',
    name: 'Highland Expressway',
    vehiclesOnRoad: 0,
    failed: false,
  },
  {
    id: 'R2_R3',
    source: 'R2',
    target: 'R3',
    bandwidthMbps: 600,
    baseLatencyMs: 10,
    currentLoad: 20,
    packetLossRate: 0.0,
    status: 'normal',
    name: 'Market Street Bypass',
    vehiclesOnRoad: 0,
    failed: false,
  },
  {
    id: 'R3_R5',
    source: 'R3',
    target: 'R5',
    bandwidthMbps: 2500,
    baseLatencyMs: 7,
    currentLoad: 32,
    packetLossRate: 0.0,
    status: 'normal',
    name: 'Central Skyway',
    vehiclesOnRoad: 0,
    failed: false,
  },
  {
    id: 'R3_R6',
    source: 'R3',
    target: 'R6',
    bandwidthMbps: 1500,
    baseLatencyMs: 9,
    currentLoad: 24,
    packetLossRate: 0.0,
    status: 'normal',
    name: 'Harbor Parkway',
    vehiclesOnRoad: 0,
    failed: false,
  },
  {
    id: 'R4_R3',
    source: 'R4',
    target: 'R3',
    bandwidthMbps: 600,
    baseLatencyMs: 10,
    currentLoad: 18,
    packetLossRate: 0.0,
    status: 'normal',
    name: 'Civic Avenue',
    vehiclesOnRoad: 0,
    failed: false,
  },
  {
    id: 'R4_R6',
    source: 'R4',
    target: 'R6',
    bandwidthMbps: 1000,
    baseLatencyMs: 13,
    currentLoad: 14,
    packetLossRate: 0.0,
    status: 'normal',
    name: 'Lowland Ring Road',
    vehiclesOnRoad: 0,
    failed: false,
  },
  {
    id: 'R5_R7',
    source: 'R5',
    target: 'R7',
    bandwidthMbps: 2000,
    baseLatencyMs: 8,
    currentLoad: 25,
    packetLossRate: 0.0,
    status: 'normal',
    name: 'East Gateway Flyover',
    vehiclesOnRoad: 0,
    failed: false,
  },
  {
    id: 'R6_R7',
    source: 'R6',
    target: 'R7',
    bandwidthMbps: 2000,
    baseLatencyMs: 8,
    currentLoad: 22,
    packetLossRate: 0.0,
    status: 'normal',
    name: 'Riverfront Way',
    vehiclesOnRoad: 0,
    failed: false,
  },
  {
    id: 'R5_S-A',
    source: 'R5',
    target: 'S-A',
    bandwidthMbps: 5000,
    baseLatencyMs: 3,
    currentLoad: 28,
    packetLossRate: 0.0,
    status: 'normal',
    name: 'Data Center Direct Feed',
    vehiclesOnRoad: 0,
    failed: false,
  },
  {
    id: 'R7_S-A',
    source: 'R7',
    target: 'S-A',
    bandwidthMbps: 5000,
    baseLatencyMs: 4,
    currentLoad: 20,
    packetLossRate: 0.0,
    status: 'normal',
    name: 'Metro Cloud Transit',
    vehiclesOnRoad: 0,
    failed: false,
  },
  {
    id: 'R6_S-B',
    source: 'R6',
    target: 'S-B',
    bandwidthMbps: 5000,
    baseLatencyMs: 3,
    currentLoad: 22,
    packetLossRate: 0.0,
    status: 'normal',
    name: 'Streaming Distribution Feed',
    vehiclesOnRoad: 0,
    failed: false,
  },
  {
    id: 'R7_S-B',
    source: 'R7',
    target: 'S-B',
    bandwidthMbps: 5000,
    baseLatencyMs: 4,
    currentLoad: 18,
    packetLossRate: 0.0,
    status: 'normal',
    name: 'Vault Interchange Spur',
    vehiclesOnRoad: 0,
    failed: false,
  },
];
